### ISSUE TITLE
Test on Thermostate mode is broken (it always provides 'negative')

### ISSUE THREAD

**Issue by lenwar** [caseda/org.eurotronic#10]
I have a flow that checks if the thermostat is in a specific mode, and if it's not it should set it as suck:

Trigger: If the temperature has changed
And:     If the thermostat mode is not "Economische" (Dutch)
            (some math.js function)
Then:    Set the thermostat to "Economische"

The first "And" line always matches even though it shouldn't (it my example it should not match, as it is already in 'Economische' mode)

![homey-thermostat](https://user-images.githubusercontent.com/3773186/47731220-f1b76080-dc63-11e8-983d-f9d277a1e4ee.png)

(( edit: added screenshot ))

**Comment by caseda** [comment]
Will be fixed in the SDKv2 rewrite

**Comment by caseda** [comment]
This should be fixed in the beta app, if not feel free to re-open this issue
