### ISSUE TITLE
Temperature calibration doesn't seam to work

### ISSUE THREAD

**Issue by ronald2404** [caseda/org.eurotronic#12]
Hello, I would like to change spirit tempature +1 C or more since it then matches my other tempature device what is more realistic. because of this i have set calibration. Tried 1 and 1,4 but it makes no difference.

![image](https://user-images.githubusercontent.com/37141942/48470792-af108f00-e7f2-11e8-9622-d7fb7ca0c297.png)

Spirit shows:

![image](https://user-images.githubusercontent.com/37141942/48470905-057dcd80-e7f3-11e8-8323-cef7cd5018da.png)

while
Aqara shows

![image](https://user-images.githubusercontent.com/37141942/48470847-df582d80-e7f2-11e8-98c9-2aa13d016010.png)

Is this a bug?

Regards

Ronald

**Comment by caseda** [comment]
This should be fixed with the latest beta
