### ISSUE TITLE
Spirit error setting external room temp setting / push temp values to valves

### ISSUE THREAD

**Issue by maja2020** [caseda/org.eurotronic#16]
version: 2.0.0 beta
homey: 2.0.0
appversion: android 2.0.2.246

Since the last homey update (2.0.0) I am unable to change the external_room_temp parameter in the advanced settings screen. Other settings can be adjusted without error. The error: 
![screenshot_20190116-095209](https://user-images.githubusercontent.com/32190313/51436777-d3c23080-1c93-11e9-9dca-95de50da6320.jpg)

- With previous homey 2.0 versions (I know for sure 2.0-rc8 and the Eurotronic 2.0.0 beta app) this was working fine. I installed the eurotronic beta app december 28. 
- All my spirit valves show this error when I change this parameter. 

I have two valves that have the external room temp setting setting enabled. The flows that push the temps from temp sensors also generate an error:  "no temperature given", but the tags are there. This is the case for all valves (so with and without the "external room temp" setting enabled).

**Comment by caseda** [comment]
found the issue and is going to be fixed in 2.0.1
