### ISSUE TITLE
Spirit, eco temperature not setable: NewTemperature not defined

### ISSUE THREAD

**Issue by caseda** [caseda/org.eurotronic#17]
Value: newTemperature,
ReferenceError: newTemperature is not defined
    at spiritSetEcoTemperature.register.registerRunListener (/drivers/spirit_zwave/device.js:240:13)

**Comment by lenwar** [comment]
I'm not sure if you want another bug report for this.
The temperature for eco temperature shows as (for example)   16&deg;    rather than the degrees sign.
Also, the temperature doesn't set for the eco temperature. (the card seems to 'hang')

**Comment by caseda** [comment]
Ah right, wanted to fix that at the same time but forgot, no issue needed, thanks for reporting

**Comment by caseda** [comment]
@lenwar i've changed certain things in the driver to be more sure that the new eco temperature is being send.
and now also the value is showing the right appendix.

**Comment by lenwar** [comment]
Hi, thanks for your quick a tions!! The degrees sign is there now, but setting the eco-temperature still hangs.

**Comment by caseda** [comment]
Hangs as in keeps spinning?

**Comment by lenwar** [comment]
Yes. It keeps spinning

**Comment by lenwar** [comment]
Hi,

No, it doesn’t. I checked on the valve and it simply doesn’t recieve or respond to it.

I now did a bit more in-depth analysis:

What I did:
I set the valve to ‘Economic’ and 12 degrees via the Homey app.
I then restarted the Homey app and verified it was still set like this. Homey said it was set like this.
I looked at the valve and the valve and it was set to 18 degrees (default for Economic mode?)
(( side note - when I touch the temperature buttons on the valve it directly goes back to Comfortable mode - so I can’t touch those for testing ))
Homey still says it’s set to 12 degrees on the app

So, I think the state currently is:
The valve is now at Economic mode 
The eco temperature is set to 18 degrees
The comfortable temperature is set to 12 degrees

To test I made a flow that after starting only changes the eco temperature to 16 degrees. This appears to do nothing

To confirm the above I did the following:
I set the valve to Comfortable mode
I restarted the Homey app and verified it was set and it was
I looked at the valve and it was set to 12 degrees (as I expected)

I also did some other small tests with other modes etc. I did not do anything with flows for this.

My conclusions:
- The temperature setting in the app on the device view always shows and changes the Comfortable mode temperature, regardless if the mode the valve is in. (I also checked this for Off and Manual)
- The default default setting for the Economic mode is 18 degrees and appears that it can’t be changed by the app at all at the moment
- I can change the Manual mode from the app and change the setting via the relevant view. This works as expected.

Suggestion:
Add another view that shows the Economic temperature setting? (Just like we have a seperate view for the manual valve.) Or at least make a read-only field somewhere for the Economic temperature.

**Comment by caseda** [comment]
Aaah now I see, it is just a mis understanding.

The target temperature in the gui **wil only** be for setting the comfortabel temperature, this is by design to stop confusion in terms of all other thermostats that work the same way, and it is impossible to tell the user that they will change either comfortable or economic with that Guage. 

As also stated in the app description, the economic temperature is only setable by **flow card**, as you useally don't set the economic temperature often (it will stay on the temperature once set), an other guage, which can not be labeled, is also not user friendly and only causes for accidental changing of the wrong temperature.

I'll see if I can add a device setting to show what economic temperature it is in, this is the most easy without people having to re-include all their thermostats
