### ISSUE TITLE
heat mode with flow went wrong

### ISSUE THREAD

**Issue by Mindsuk** [caseda/org.eurotronic#18]
I use the latest beta 2.0.0

I made a flow to change the heat mode to off, if the window in our kitchen will be open. I wondering why it won‘t work! Then I realized that my Spirit in the living room was off instead of the Spirit in the kitchen. If I start the flow for the kitchen manualy, the Spirit in the living room change the heat mode to off! That‘s strange, isnt it??
But, if i change the heat mode for the kitchen manual within the Homey App, the right Spirit goes off!

**Comment by caseda** [comment]
The UI option and the Flow option use the exact same part of the code, so yes it is weird.
are you sure you selected the right device in your flows?

**Comment by Mindsuk** [comment]
Hi caseda, Yes, I defenitely selected the right device! The first called Heizung Küche, the other one called Heizung Esszimmer.

**Comment by caseda** [comment]
I've changed some checks in the app now to be more sure the device that needs to be controlled, is the one that is being controller, hopefully that will fix your issue.

you'll see the update soon (v2.0.2)

**Comment by Mindsuk** [comment]
Thanks a lot! I will try it as soon as it is available

**Comment by caseda** [comment]
Update is in the app store

**Comment by Mindsuk** [comment]
Sorry, but the problem still resists! 😐

Let me explain the problem more in detail. 

I create a flow: 
when: this flow is started
then: Heater kitchen, Set thermostat mode to off

If I start this flow, die Heater in the Living room will be set to off!

No matter, which Heater I use within the Flow. Everytime the Heater in the Livingroom will be set to off! Thats crazy!

Sorry for my bad english! Hope now you understand whats the problem.  🤷🏼‍♂️

**Comment by caseda** [comment]
Your English is just fine.

You are the only one that has it until now, so I really doubt it is the app now.
Especially with the amount of checks now going on that the right device can only be controlled

**Comment by caseda** [comment]
Could you post a screenshot of your flows?

**Comment by Mindsuk** [comment]
Thank you! 😊

Do you mean the Homey v2 App? Should I report it directly to Athom?

Yes, i could show you my Test Flow!
But how could I send you a screenshot?

**Comment by Mindsuk** [comment]
Ah, okay! Now I see it. 

![613ea26f-72f7-4fd1-8dcd-70373d1dca2b](https://user-images.githubusercontent.com/27997724/51760167-1fc50900-20ca-11e9-8f60-0080093d97f4.png)
![c14a12f7-69ed-4b15-a0a2-08c6e5f4d3d0](https://user-images.githubusercontent.com/27997724/51760168-1fc50900-20ca-11e9-952f-ae5da4659669.png)

**Comment by Mindsuk** [comment]
After hitting Test, the 2nd Heater in the Living room went to off.

**Comment by caseda** [comment]
Someone else now confirmed that it is not fixed yet.

I do know how it can be fixed, completely, but it will need a little investigation how that implementation really works, not sure when I have time for that as I'm not at home currently.

**Comment by Mindsuk** [comment]
@caseda Ok, good to know that I‘m not the one and only! 😉

I will cross my fingers and wait

**Comment by Mindsuk** [comment]
Good evening! I‘ve got more details for you. A colleague of mine tried it too and had the same result! But now it‘s clear that the flow trigger only the last included Spirit!
My last one was the Spirit called „Heizung Esszimmer“! Every flow I tried, triggers this Spirit!

Hope this help a little bit

Greetings Tino

**Comment by caseda** [comment]
Well, didn't really need the info as I already knew how to fix the issue, though did think it was the first included device, so did learn something 😝.
I'll try to implement the fix this weekend.

**Comment by caseda** [comment]
ok, v2.0.4 should definitely fix your issue, if not then i'll have to buy myself a second thermostat and hope i won't get bold from not understanding, why!?.

**Comment by Mindsuk** [comment]
I will test it and give you an feedback 😉🤜🏻🤛🏻

**Comment by caseda** [comment]
Update is online in the app-store, keep me updated :+1:

**Comment by Mindsuk** [comment]
now it functions! 👌🏻

**Comment by caseda** [comment]
Awesome, thanks for the swift testing, and sorry for any caused inconveniences.
