### ISSUE TITLE
Beta 2.0.0 app crashes when setting eco temperature.

### ISSUE THREAD

**Issue by lenwar** [caseda/org.eurotronic#19]
Eurotronic App version 2.0.0 beta
Homey firmware 2.0
Homey Android app version: 2.0.2
Valve type: Spirit

Diagnostic report ID: 0e27c4b5-171b-4787-bc2e-f267aaae2882

When I try to set the 'economic temperature', the cards go grey and say (Dutch error) "Dit kaartje is onbeschikbaar" for a few seconds.  This happens both when using a 'Logic variable' as a target temperature and when using the temperature slider.

I don't know if it's related, but the temperature slider doesn't properly show a degrees-sign: "16&deg;C" rather than "16°C"

**Comment by caseda** [comment]
Already made an issue for it yesterday (#17) to keep track of it when it first came in, but thanks for reporting.

But the view in the slider is unrelated.

**Comment by lenwar** [comment]
Apologies. I didn't notice that. (or at least, I didn't link that error to mine in my mind)
