### ISSUE TITLE
Direct Control

### ISSUE THREAD

**Issue by breem** [caseda/org.eurotronic#2]
Hi,

Well... Issue... More like a question.

I tried to ad a fourth option of the StellaZ device's "eurotronic_mode" to directly set the valve position of the StellaZ. This is a documented option and for me very useful for implementing the StellaZ in combination with Floor heating.

After adding this option at all places I think necessary and testing the app on Homey I get the following message:
? Select active Homey: Homey @ 192.168.1.109:80
1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.1.109:80...
capabilities.eurotronic_mode: invalid_title

Does this ring a bell? How to proceed from here? Thanks in advance for any reaction.

**Comment by caseda** [comment]
hope you do know that it is more work then just add that mode to the mode selector 😛 

but you probably did not add everything to app.json and the driver.js that has to do with the modes

**Comment by breem** [comment]
Hi,

Tried to fill in the mode change in the app.js. But I was looking for the place where the driver sends the THERMOSTAT_MODE_SET command to the device. From the documentation you refer to in the code:
Frost Protection: BASIC SET 0x01, THERMOSTAT MODE SET 0x00
Energy Saving: BASIC SET 0x00, THERMOSTAT MODE SET 0x0b
Comfort: BASIC SET 0xff, THERMOSTAT MODE SET 0x01
Direct Control: BASIC SET 0xfe, THERMOSTAT MODE SET 0x1f

When I search the code for the values 0x00, 0x0b or 0x01 I get no results. Can you point me in the right direction? Thanks in advance.

**Comment by caseda** [comment]
in homey we don't work with hex, most (99%) of the commands are converted in the z-wave core from decimal to hex, no need to set the hex values for that.
```
module.exports = new ZwaveDriver( path.basename(__dirname), {
	capabilities: {
		...
		'eurotronic_mode': {
			'getOnWakeUp': true,
			'command_class': 'COMMAND_CLASS_THERMOSTAT_MODE',
			'command_get': 'THERMOSTAT_MODE_GET',
			'command_set': 'THERMOSTAT_MODE_SET',
			'command_set_parser': value => {
				return {
					'Level': {
						'No of Manufacturer Data fields': 0,
						'Mode': value
					},
					'Manufacturer Data': new Buffer([0])
				};
			},
			'command_report': 'THERMOSTAT_MODE_REPORT',
			'command_report_parser': report => {
				if (report.hasOwnProperty('Level')) {
					/* Value: Off - Name: Off
					 * Value: Heat - Name: Comfort
					 * Value: Energy Save Heat - Name: Economic
					 */
					return report.Level['Mode'];
				}
				return null;
			}
		}
	}
});
```

If you see the `manufacturer data` object, it is a node.js function to convert decimal to hex (`new Buffer([])`)
this was needed since this command class was not fully implemented, i don't know if it is now since there was an update to the core afterwards.

everything in the set_parser is what is being send to the module, and is needed to set the mode.
the value is the "values.id" in the capability inside app.json

**Comment by breem** [comment]
Hi,

I almost got it to work... I added the direct control mode and I can set it from the interface within Homey. Bu I can't find out the value.id needed to set the THERMOSTAT_MODE.

In debug mode I see the following:

--> Set mode to economic
[debug] set eurotronic_mode Energy Save Heat
[debug]  COMMAND_CLASS_THERMOSTAT_MODE
					->THERMOSTAT_MODE_SET args: { Level: { 'No of Manufacturer Data fields': 0, Mode: 'Energy Save Heat' },
  'Manufacturer Data': <Buffer 00> }

--> Set mode to direct control
[debug] set eurotronic_mode Direct Control
[debug]  COMMAND_CLASS_THERMOSTAT_MODE
					->THERMOSTAT_MODE_SET args: { Level: { 'No of Manufacturer Data fields': 0, Mode: 'Direct Control' },
  'Manufacturer Data': <Buffer 00> }
[debug] [ { [Error: invalid_value ["Level"]] message: 'invalid_value ["Level"]' } ]

How did you find the code "Energy Save Heat"? I can't find this in the documentation of the StallaZ.

**Comment by caseda** [comment]
it's in the z-wave specification files.
http://zwavepublic.com/specifications

**Comment by caseda** [comment]
just curious how the progress is going, and if you are able to succeed.

when i'm done with looking into an weird issue(s) in another app of mine.
i'll look into adding this functionality
(maybe end of this week, but probably next week)

can't test this myself though, so need you or someone else to test it for me.

**Comment by breem** [comment]
Due to a combination of me being new to node.js and too much to do I did not get very far until now. I bumped into two problems:
1. Which code to send to the StellaZ to activate direct control mode.
2. In the mobile app I wanted to relace the temperature control by a slider to control the valve position.

Regarding to problem 1 I am trying to write a small app that sends a zwave command to the device and log the results to the console, no success so far...

I posted problem 2 in the Homey forum, I don't know if this is possible at all.

I'll be happy to test if you get any further then I got.

**Comment by caseda** [comment]
Option 1 I already know which one. 

Option 2 is not possible, unless athom implements a new type of capability for that, but for 90% sure that won't happen since they already have something that you can control it with (dim slider). 
Will ask if such a thing will be made possible, but won't give it a high chance

I've gotten pretty far with the issue(s) of the other app, so if that keeps up, I will give it a shot at the end of the week.

**Comment by caseda** [comment]
ok, i have added the manual control to the repository, if you would be so kind to test it for me. 😄
put some small explanations in the commit

**Comment by breem** [comment]
Great, tnx! I jus tried to run the new version and go an error:

1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.1.104:80...
3/4 - Running `org.eurotronic`, press CTRL+C to abort...
4/4 - Debugging...

-------------------------------------------------
org.eurotronic running...
SyntaxError: Unexpected token !
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /homey-app/manager/drivers.js:74:27
    at Array.forEach (native)
    at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)
    at /homey-app/manager/drivers.js:20:38
    at /homey-app/homey.js:1:1145
    at Array.forEach (native)
    at Object.<anonymous> (/homey-app/homey.js:1:1123)
    at emitNone (events.js:67:13)
    at Object.emit (events.js:166:7)
    at /bootstrap.js:230:9
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

--- INFO: org.eurotronic has been killed ---

**Comment by caseda** [comment]
whoops, removed a little bit too much in one of the 2 drivers :blush: fixed now

thought i checked everything with my code checkers, but that somehow got through

**Comment by breem** [comment]
Got it running now. Thanks for the quick repair!

I tried a flow setting the valve position to 80% and got an error message "unknown_error" in the action card. I think this is caused by the wrong thermostat mode. I'll be testing some more this week, will let you know the results.

**Comment by caseda** [comment]
No, unknown error is something else, it should change the mode to manual mode when it is not in manual mode, if it fails at that it will give that message and stop the flow card. 

Can be that the flow did go true, but that error message overwritten the right message. 
Please check the mode status of the valve if it really has changed. (maybe after wakeup)
If so I will need to make a change in the flow control.

**Comment by breem** [comment]
I waited some time (verified communication in the ZWave log with the node I was testing with). After the communication I saw I checked the mode on the device. It was not at manual mode.

**Comment by caseda** [comment]
ok, i made a change in the flow controller and should work properly now, even when mode was not yet on manual (i think it was because the mode was not available in homey yet after startup of the app, now the controlling takes that into consideration)

**Comment by breem** [comment]
I downloaded the new commit. I have been testing with two radiator valves. First I tested to set the valve position of device 1 and the temperature on device 2. Device 1 returned "unknown_error", device 2 returned successful.

Next I tested to set the mode to manual on both devices. Both devices returned "unknown error". Right after that I saw the tracelog below on the console:

1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.1.104:80...
3/4 - Running `org.eurotronic`, press CTRL+C to abort...
4/4 - Debugging...

-------------------------------------------------
org.eurotronic running...
ReferenceError: value is not defined
    at /drivers/stella_zwave/driver.js:268:69
    at process.<anonymous> (/homey-app/helpers/client.js:1:1269)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at internal/child_process.js:721:12
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

--- INFO: org.eurotronic has been killed ---

**Comment by caseda** [comment]
Woops that crash is my bad, at least it gave me the insights that the mode was send properly at least.

the rest is a little bit puzzling to me why it ends there...
have added a few extra lines of debug to see where it stops at, viewable in CLI

sorry for the inconvenience 😅 but thank you very much that you want to test for me 😄

**Comment by breem** [comment]
No problem, I asked for it ;)

I tested the new commit and it looks like we are getting further...

In the attached screenshot you can see my test.
![screenshot from 2017-04-19 21-06-31](https://cloud.githubusercontent.com/assets/5067058/25198330/6c011438-2547-11e7-8f52-0db73d93cc1c.png)

The error shown in the action cards: mode_set_Error: invalid_value ["level"]

After some further manipulation i doubt if the valve position is actually set... I don't hear the valve opening or closing at the moment the CLI returns "Succesfully changed to x%"

**Comment by caseda** [comment]
hmmm, so only the mode isn't set yet... i'll have a look why it says invalid value, maybe it's not parsed to `Manufacturer Specific` in homey's z-wave core...

old information (sept '16) shows 'MANUFACTURER SPECIFC' which is kinda odd way of saying this mode (should have looked that before hand 😅) but since it is old information it might have changed/updated.

i'll see if athom can/is willing to give me the info first hand, otherwise we need to get the real naming via a command (that i first need to find again).

**Comment by caseda** [comment]
have had "confirmation" (not really.. :joy:) that it probably is still the typo version of the ID.
so have changed all ID's and should work now...

if not, i will add a command so it will show all ID's it supports (and doesn't)

**Comment by breem** [comment]
Sorry for the delayed response, I've been busy the last few days.

I think you ailed it with this last commit:
![screenshot from 2017-04-23 20-37-43](https://cloud.githubusercontent.com/assets/5067058/25316313/fd5f15b8-2864-11e7-95ba-82764265388f.png)

And I heard the valve actually opening after this command

**Comment by caseda** [comment]
Yeah of course that should be possible, and I think easy to add, I'll look into it :+1:

It is already a global tag, main reason why I made a custom capability.
Will also make it easier to add the insights (think it's only 1 extra line) 
Think you will have to re-include though.

**Comment by caseda** [comment]
OK, i have changed the last things to the driver:
removed the debugging tekst again, since it works now 😄 

added a chart type, that should activate the insights once a new value is received/send.
but you might need to re-pair if you haven't done that yet since the capability was added.

also saw in the debug that the mode was send after the start of the "if" for the value to be send.
in theorie this should always go right, but if for some reason it slows down the send of the mode, i've added a small delay of 300 milliseconds, just to be sure it really is send before the value.
But only happens if the mode also needs to change.

Just keep testing it this week, if it keeps working properly this week i will put it into the app-store

**Comment by breem** [comment]
I have been running the app for a week now. No complaints from my family members about a cold house ;)

The original actions are working fine as well as the newly added manual control as far as I have tested.

Thanks again for adding this to the app! As far as I am concerned this app is ready for the app store.

**Comment by caseda** [comment]
still did some small (mostly textual) changes 😛

but those won't break anything
have just send in the 1.1.0 update towards the app store.

thank you very much for this testing periode 😄 and your (precious) time

**Comment by caseda** [comment]
closing it now, it is implemented in the app store

again thanks ❤️ 

still something comes up you can create a new issue for it.
