### ISSUE TITLE
External temperature value not working 

### ISSUE THREAD

**Issue by JustThe2ofUs** [caseda/org.eurotronic#23]
The option is enabled in advanced settings, a flow (WHEN temp of external sensor changes THEN send temp value to Valve) is created. 

However: it doesn’t work. The temp value of the external sensor is not recognised nor shown in the app. Furthermore there is no variable in the webDev App that’s showing a handover of the temp data. 

Therefore there is no proof at all for this on working. 
eg the valve shows 16 degrees while the ext sensor reports 19 degrees. As the temp at the valve wa set to 18.5 degrees it says “heating towards” (15 -> 18.5). This tells me it simply is not working.

**Comment by caseda** [comment]
As already explained in the forum post, there is no way for me to verify the send room value, if I retrieve the temperature the valve will just give me its own last measured temperature.

If you really want to see the transfer you'll have to look at the _zwave log_ in the developer tools.
And the check icon shown in the flow card is only given if the valve actually said "ok I received your signal" after sending the room temperature.

You really will have to look at the valve itself, maybe even enable the manual control value in the advanced settings that it really is closing, what homey tells you is not what the valve actually does, and also not possible to fully sync either.

**Comment by caseda** [comment]
in v2.0.4 i set the flow card's value as measured temperature (even though it is a little bit placebo, it will only get set if the valve said to receive the value properly), so you at least know what the last send (room) temperature is.

**Comment by Mindsuk** [comment]
It‘s working now, too!! 👌🏻👌🏻👌🏻👌🏻
