### ISSUE TITLE
Valve position not in insights

### ISSUE THREAD

**Issue by topkock** [caseda/org.eurotronic#26]
Hi, 
Could you please add valve position to insights? This would really help, since now I'm trying to gain insight manually, since I would like to try out a flow that's driven on valve positions with temp feedback..
Thanks

**Comment by caseda** [comment]
I'll see if I can add that

**Comment by caseda** [comment]
will be added in the 2.0.5 release, now pending approval

**Comment by topkock** [comment]
ok great thanks.
how come I cannot see the latest version here on Github? That way I could already install and test after uploading via CLI...

**Comment by caseda** [comment]
It is on github otherwise I couldn't upload it to the appstore.
You need to have the [SDKv2 branch](https://github.com/caseda/org.eurotronic/tree/SDKv2)

**Comment by caseda** [comment]
App is to be found in the appstore (beta channel).
