### ISSUE TITLE
request_timout since last update?

### ISSUE THREAD

**Issue by topkock** [caseda/org.eurotronic#27]
thanks for adding valve-position to insights.
However since a few days (I think right after the last update) there seems to be very poor connection to my Spirit. I constantly get timout errors.
Potentially related to any of the last changes? It seems better if Homey is closer to the valve, but no problems before and only 5 meters away in adjacent room....

**Comment by caseda** [comment]
Me as app creator can't do anything to improve or decrease the range, that is all taken care off by homey's zwave core. (that includes any timeouts or no_ack messages)

Try rebooting your homey by removing the power plug for several minutes, see if that helps.
There are several people with FLiRS devices that have trouble (homey issue), though Eurotronic devices apparently stay pretty stable in that matter.

**Comment by caseda** [comment]
Woops accidentally closed, wrong button to comment

**Comment by caseda** [comment]
as i can't do anything about range or FLiRS issues that are all homey, i will close this issue
