### ISSUE TITLE
show comfort temperature while Spirit is in Eco Mode

### ISSUE THREAD

**Issue by Mindsuk** [caseda/org.eurotronic#28]
Hi!

Within Homey I still see only the comfort Temperatur, while the Spirit is in Eco mode. but the Spirit show the eco temperature on his display. Could you do something to fix thar?

Greetings

**Comment by caseda** [comment]
i will not add this in the app, it is too difficult to implement correctly, and way to prone of errors.
And might cause confusion for people as the GUI always will show target temperature of the comfort mode, not just this device or app, but all thermostats in homey.
