### ISSUE TITLE
radiator warm while off

### ISSUE THREAD

**Issue by ronald2404** [caseda/org.eurotronic#29]
Hi I am using the beta app and noticed that not all Valve are really off when turned off.
Also i noticed I that the 'Handmatige positie" value of one of my 4 Spirits is different: where does this come from? I would expect to see the same 'Handmatige positie" value if running in same mode like uit, eco, or comfort

**Comment by caseda** [comment]
Does the thermostat show off as well?
If so then it is not an app issue. 

Manual position is based on how far the valve is open, the lower the value, the more closed the valve is, and is completely dynamic based on target temperature vs measured temperature (it slowly closes the more near it gets to the target value).
By default this value is not send by the device (to save battery), only gotten during boot of the app, if you want it being reported, then you'll have to enable it in the advanced settings.

**Comment by ronald2404** [comment]
Thanks let me check and get back to you.


Regards Ronald

Op wo 13 mrt. 2019 17:32 schreef R Mengers <notifications@github.com>:

**Comment by ronald2404** [comment]
I believe I now understand the cause. The valve was disabled but the set
temperature was higher then actual temperature. Do you agree?

Another question how can you force an update on the measure temperature?
I have one device with 5 day old values.

Also I wonder when are the valve mode changed? When I switched to comfort
or other via the app it is not always saved. It looks like you have to wait
or click on the modes after changing it.

I do have to say I really like the 2.0 app!
Thanks for the hard work!

Op wo 13 mrt. 2019 17:32 schreef R Mengers <notifications@github.com>:

**Comment by caseda** [comment]
even though the measured temperature in homey is wrong, the valve itself should correct itself internally, measured temperature getting near target temperature is all taken care of by the module, not this app or homey.
As it is most likely not an app issue, i will close this one
