### ISSUE TITLE
Spirit Z-Wave lost (external) Room Temperature

### ISSUE THREAD

**Issue by MAIKDO** [caseda/org.eurotronic#30]
The Spirit Z-Wave Thermostat would be set to (external) Room Temperature.

The external value is temporarily lost.

On Homey Insights this can be understood via the evaluation.

example:
Spirit Z Wave Thermostat
2019-05-15 02:10:00	19.3
**2019-05-15 02:15:00	17.03899999999998
2019-05-15 02:20:00	16.63999999999998
2019-05-15 02:25:00	16.63999999999998**
2019-05-15 02:30:00	19.3

External Sensor
2019-05-15 02:10:00	19.3
2019-05-15 02:15:00	19.3
2019-05-15 02:20:00	19.3
2019-05-15 02:25:00	19.3
2019-05-15 02:30:00	19.3

APP Version V2.06
Firmware-Version Eurotronic Z Wave: 769

[Archiv.zip](https://github.com/caseda/org.eurotronic/files/3181586/Archiv.zip)

**Comment by motom001** [comment]
Confirm this issue.
It seems a problem, when the external temp could not set. So the device use as fallback the own temp.

**Comment by caseda** [comment]
sorry for the late response, yes apparently the valve does still send its measured temperature even though mine never did when it went into external temperature mode, i will have to catch that in a way.

But i'm not sure when i have time for this, sorry for any inconvenience

**Comment by caseda** [comment]
This should now be fixed in the latest app update.
