### ISSUE TITLE
Heating valve keeps reporting temp change on homey app

### ISSUE THREAD

**Issue by ronald2404** [caseda/org.eurotronic#31]
Hi,

My Valve is reporting for about every 10 minutes a popup saying: Temperatuur slaapkamer veranderd.

I have disabled the app and also the notifications. How is this possible?
It would be great if you can enable popups per valve.

Regards
Ronald

**Comment by caseda** [comment]
Not sure what you mean with popup, I don't show/give any popup at all with the app so definitely not an app issue. 
I am curious though, could you gave a screenshot of the popup?

**Comment by ronald2404** [comment]
Notification on my phone is what i mean.  Ill take a screenshot and share it

**Comment by caseda** [comment]
I don't send any notifications with the app, you probably made a flow for it.

**Comment by ronald2404** [comment]
Nope, I just checked I have all my heating flows disabled because of the summer

**Comment by caseda** [comment]
The last edit of the app was even before apps could create notifications, have not invested any time at all to even look at such implementation as it is already possible with flows, so 100% sure it is not my app that is sending notifications to your timeline

**Comment by ronald2404** [comment]
Thanks for your support. After disabeling all flows issue is solved. Next step is figure out which flow is causing the issue.

Regards Ronald

**Comment by caseda** [comment]
good luck with finding the culprit flow.!
