### ISSUE TITLE
Spirit Z-Wave not stable connection, strange mesh paths

### ISSUE THREAD

**Issue by DarkBeardRUS** [caseda/org.eurotronic#34]
Spirit Z-Wave not stable connection, strange mesh paths of the way, even devices in direct line of sight (2 meters without barriers) connected to the hub through the next room! To deliver settings, you have to transfer them constantly, every minute, all the time.

**Comment by caseda** [comment]
Thank you for reporting.

Unfortunately i have no control **at all** over these things (paths/routing), and you'll have to contact Athom for how to fix these kind of issues.

As it has nothing to do with this app i will close this issue, please contact Athom.
