### ISSUE TITLE
Change temperature indicator in icon right above

### ISSUE THREAD

**Issue by JackDaniel007** [caseda/org.eurotronic#35]
First of all, thanks a lot for the app (works perfectly with my spirit z valves ):)
Would it be possible that when the mode is off not 8 degrees are displayed but 0 or even off?
Thank you in advance.

**Comment by caseda** [comment]
off isn't "0 degrees" for the spirit thermostat, so that doesn't make sense.
but anything else then a number isn't possible, so "off" isn't possible.

it is just completely based on the target_temperature capability, can't change much about the GUI itself, you'll have to contact Athom for that.
