### ISSUE TITLE
Spirit Z-Wave - not able to set protection via flow

### ISSUE THREAD

**Issue by carmei** [caseda/org.eurotronic#37]
Hi, tried to change the protection status of my spirit device based on flow without success. Tried to protect the device in Mode ECO, Comfortable, manual, in all cases the status is not changeable.

**Comment by carmei** [comment]
Additional info. I ckecked the screen of the spirit and the locked icon is shows as expected. When I check the extended settings of the spirit the protection tag still shows unprotected and based on this i receive still the feedback within the notification push on my mobile that the device protection status is unprotected.

**Comment by carmei** [comment]
Finally, the device is locked and the display of the spirit shows the correct setting and the info of the device within homey is correct.

**Comment by caseda** [comment]
Just for your infomation, the protection state (child protection) is only for the _physical buttons,_ not anything Homey can do, Homey can still do/change everything when the protection is on.

As for the state not changing, this seems more like a range issue, nothing to do with the app.

**Comment by carmei** [comment]
Hi, first sentence is clear, but I don’t think that we talk about a range issue. The range is the same when I change the protection state manually via the extended setting of the spirit, that works and shows the correct value of the var protection status or when I use a flow and the sprit shows the protection status correct but the var protection status still has the value unprotected.

**Comment by caseda** [comment]
This bug has been fixed in the [Test version](https://homey.app/nl-nl/app/org.eurotronic/Eurotronic-Technology-(Z-Wave)/test/) (v2.2.0), enjoy.
