### ISSUE TITLE
Z-wave Spirit - Background light goes on & off constantly after upgrade to 2.0.7

### ISSUE THREAD

**Issue by gewu60** [caseda/org.eurotronic#38]
Disabling the function within the app has no effect.

I've created a diagnostic report 19f45dc2-0120-4520-a2df-64cb283621ab

**Comment by caseda** [comment]
please explain your self more, as there are only 2 options within the thermostatic itself:
- ON, for it being on, and off after 5 seconds i think the timeout is
- OFF, for it always being off

**Comment by caseda** [comment]
bump

**Comment by gewu60** [comment]
You can close this one
