### ISSUE TITLE
Unable to set target temperature

### ISSUE THREAD

**Issue by rzarajczyk** [caseda/org.eurotronic#39]
Eutortonic Spirit: The temperature panel displays "current temperature" correctly, but instead of target temperature I can only see the dash and cannot set it. See screenshot.
![Screenshot_20191024-000854_Homey](https://user-images.githubusercontent.com/4639652/67437974-81cb8400-f5f2-11e9-8d0b-099451dffb5d.jpg)

The diagnostic report from Homey is c9b43aef-6d00-48c2-96d7-c79e372b28df

App version is v2.0.6 beta, automatic updates are enabled, Honey 2.5.2

**Comment by caseda** [comment]
Thank you for reporting, unfortunately your log doesn't say anything useful so most likely nothing I can do about it, what's the distance between the valve and Homey? (or another mains powered device if it is being routed)

**Comment by rzarajczyk** [comment]
The distance is about 2 meters, so it's very close.
Actually after I posted I found a workaroud - I was able to set the temperature via automation, and once I did it - the app panel started working!

**Comment by caseda** [comment]
Good to hear that it works now, as I have no further control over this I can't enhance this, but something to keep in mind if it ever happens again with someone (apparently doesn't happen often as you are the first that mentions it)
