### ISSUE TITLE
Spirit z-wave valve issues

### ISSUE THREAD

**Issue by gizmodok** [caseda/org.eurotronic#40]
Hi,

The heating season had begun and I bought 2 extra eurotronics spirit z-wave.

I have experiencing a very strange glitch. When I go sleep I set the temperature to 8 degrees Celsius. When I wake up I see that in the room is 24 degrees but on the display is still 8 degrees. I turn it to off mode and I hear that the valve is closing completely and than again to 21 or so I hear and it works fine. 

I can’t really explain it this glitch I have on both thermostats a few times now.

At first I thought that the external temperature sensor is not sending right temperature but after checking it the every thing was fine. 

It can be still an issue with a external temperature reading but I can’t check if the variable is in the food place. In the app I can see that sensor is getting a good reading.

It looks like the valve isn’t closing when set to low temperature but it hangs on the old temperature setting and it’s ignoring the temperature sensor.

Furthermore everything is working great but that issue is quite frustrating.

I will send logs to this issue it happend yesterday night.

Many thanks

**Comment by gizmodok** [comment]
dadd91aa-1640-4073-9c64-02fe95bf8db1

**Comment by gizmodok** [comment]
One small update, after the issues with the valve the thermostaat is not working correctly until it’s rebooted. I take battery out. Than everything works fine.

**Comment by pear7777** [comment]
Hi, This is the first time someone mentions the same as I have.

I hav e Homey with 5 connected spirits, and all of my rooms are heated to way higher than what I set the spirit to.

Let's try and get to the bottom of this together, since I have ditched them all, sett me back a €250.

**Comment by remcodk** [comment]
I'm facing some kind of the same issue. I have 5 Eurotronic spirit devices connected. And tested for hours now with the external setpoint setting. When I configure it to use an external measurement from a flow (and enabled ext. temp in settings offcourse), it sends it correctly to the spirit. But the spirit is just ignoring this and using it's interal measurement. I've tested this by sending the ext. temp of 35 to the spirit (and received by the spirit). The spirit just keeps heating on it's internal measurement I think. Only when I adjust the target setpoint in steps of 0.5 degrees through Homey I hear the spirits' motor turn in small steps.

I hope this can be fixed. It would be great to have this setup running correctly.

**Comment by caseda** [comment]
if the screen does show the send new and correct temperature, then i'm not sure why that would be an app issue as i have no control over the thermostatic at all, especially if the external temperature isn't used.
so please contact eurotronic how this can happen, as it is most likely a firmware issue of the thermostatic themselves.

**Comment by pear7777** [comment]
You know, that could b eright, since the overheating ahppens too if I set alle settings, and just switch off homey,  Can we expect the thermostat to work autonomically?

**Comment by pear7777** [comment]
Additional information: Eurotronic mentioned:
"we have had to find out that a faulty component has crept into the delivery batch for autumn 2019. "
They state that they will switch the faulty devices, just mail at Info@eurotronic.org.

**Comment by pear7777** [comment]
I received replacement thermostats, installed all seven, and they all work great. No more overheating.

**Comment by caseda** [comment]
as this issue has been resolved by changing out the device itself, confirming that it isn't an app issue, i will close this one.
