### ISSUE TITLE
App does not recognize AEOTEC labeled devices

### ISSUE THREAD

**Issue by chiboodle** [caseda/org.eurotronic#44]
Theres are variants of the Z-wave thermostat which are labeled as AEOTEC devices. Those are only recognized as general Z-wave device. Would be great if they also would ne supported.

**Comment by caseda** [comment]
Aeotec boxed version is now supported in the [Test version](https://homey.app/nl-nl/app/org.eurotronic/Eurotronic-Technology-(Z-Wave)/test/) of the app (v2.2.0), sorry it took a bit longer then expected, but enjoy!
