### ISSUE TITLE
Support for Z-Wave Sensors

### ISSUE THREAD

**Issue by bobvanoijen** [caseda/org.eurotronic#47]
On the Eurotronic website I see they also have Z-Wave [sensors](https://eurotronic.org/produkte/sensoren/).
-[LUFTGÜTESENSOR Z-WAVE PLUS (VOC-SENSOR) ](https://eurotronic.org/produkte/sensoren/luftguetesensor/)
-[TEMPERATUR-FEUCHTE-SENSOR](https://eurotronic.org/produkte/sensoren/temperatur-feuchte-sensor/)
Any plans on supporting these as well?

**Comment by caseda** [comment]
The app has been transfered to Eurotronic itself recently, but see the (test app)[https://homey.app/a/app/org.eurotronic/Eurotronic-Technology-(Z-Wave)/test] for more information on the sensors 😉

As it has been transfered I will close this issue.
