### ISSUE TITLE
Eurotronic Spirit

### ISSUE THREAD

**Issue by Bhitv** [caseda/org.eurotronic#6]
Hello Remco Mengers

I have installed 2 Eurotronic Spirit.
1 worked perfectly.
The other gave problems and I removed them from Homey.
At least, that was the intention.
Homey indicates that he has been removed, but he is still in my devices.
He is also displayed in the network.

I could pair the device with homey again, but the old one stayed in it
See Figure 38 is the new link and working properly.
37 must actually have disappeared.

Can I fix this?
Bernard

![2018-03-01 22_21_59-settings - homey](https://user-images.githubusercontent.com/24967334/36902702-b4b5d7e4-1e2b-11e8-8343-b61c43bd9bf4.jpg)

**Comment by caseda** [comment]
You can remove a device that is already reset, if you click the X on the device, and let it time out

**Comment by Bhitv** [comment]
Yes, you are right.
It works, he has disappeared from the list
Thanks for the tip.

Bernard
