### ISSUE TITLE
Sometimes no communication to Spirit valve

### ISSUE THREAD

**Issue by Eternity-again** [caseda/org.eurotronic#7]
This morning I discovered that 1 of my 4 Spirit valves had not decreased it's set temperature, as was 'instructed' by a flow.

I made a test flow with 2 Spirit valves, and oddly enough every time one of the 2 valves has a communication problem. One works, one gets a red triangle, next test after some second, this happens again, but now the other Spirits gets a triangle.

I put both Spirits in the same flow and added an extra card to do the same temperature set, but after 15 seconds. This is the result:
<img width="1062" alt="schermafbeelding 2018-03-19 om 18 34 53" src="https://user-images.githubusercontent.com/10754229/37613315-fd9698e8-2ba7-11e8-81e2-461d58d6799b.png">

The Spitits mesh shows this: 
<img width="984" alt="schermafbeelding 2018-03-19 om 18 57 08" src="https://user-images.githubusercontent.com/10754229/37613413-437fdbbc-2ba8-11e8-8ff4-ac633820bd11.png">
So, they 'hop' via another node.

On the same first floor I have another Spirit that has a direct link to Homey:
<img width="992" alt="schermafbeelding 2018-03-19 om 18 57 39" src="https://user-images.githubusercontent.com/10754229/37613333-09b1c328-2ba8-11e8-9d50-1a1f8c2a2a88.png">

**Comment by rogierhofboer** [comment]
Same here. Worked on Homey 1.5.3 now on 1.5.12 it stopped working for Spirits connected via another node.

**Comment by rogierhofboer** [comment]
Seems to work now, in the sense that the Spirit is updated from the Homey. But changes on the Spirit are not seen by the Homey. So when at 18 degrees, changing to 17 degrees on the valve itself, keeps the Homey app at 18 degrees. I've never had any issues like this with 1.5.3

Could it be the the z-wave changes in 1.5.13rc11 fix this?

**Comment by caseda** [comment]
i have just finished up SDKv2 rewrite of the app, this won't improve range of course but just so you know.

as this is indeed not an issue that i can fix with the app but is an homey range issue, i will close it.
