### ISSUE TITLE
Spirit Z-Wave Thermostat does not adapt external room temperature

### ISSUE THREAD

**Issue by carmei** [caseda/org.eurotronic#9]
Hi, I added 2 Spirit Z-Wave Thermostats to my Homey and additionally one Devolo Roomthermostat. 
I changed the setting of the Spirit device - setting "External Roomtemperature" from unabled to enabled.
I added a flow like this: When "The temperature (not target temp) changed (Devolo)" then "Send room temperature #temp to Spirit Z-Wave". Additionally the flow also send me the #temp to my mobile.

Devolo device is working as expected based on the info I received on my mobile, but when I check the shown temperature of the Spirit afterwards, it shows its own temp measurement. I tried it with both, Spirits, same result. Except backlight of and screen rotation, all Spirit settings are the default ones.

Many thanks for your support.

Carsten

**Comment by caseda** [comment]
It will not show its received "external" temperature, that is a limitation of the device that I can not change. 
It will react to the external temperature though.
